require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe HoraDeFuncionamentosController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # HoraDeFuncionamento. As you add validations to HoraDeFuncionamento, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
{
    dia:"20/07",
    inicio:"8:00",
    fechamento:"22:00",
} 
 }

  let(:invalid_attributes) {
{ 
   dia: nil,
    inicio: nil,
    fechamento: nil,
} 
 }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HoraDeFuncionamentosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "returns a success response" do
      user = create(:user)
      sign_in user
      HoraDeFuncionamento.create! valid_attributes
      get :index, format: :html, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      hora_de_funcionamento = HoraDeFuncionamento.create! valid_attributes
      get :show, params: {id: hora_de_funcionamento.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      hora_de_funcionamento = HoraDeFuncionamento.create! valid_attributes
      get :edit, params: {id: hora_de_funcionamento.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new HoraDeFuncionamento" do
        expect {
          post :create, params: {hora_de_funcionamento: valid_attributes}, session: valid_session
        }.to change(HoraDeFuncionamento, :count).by(1)
      end

      it "redirects to the created hora_de_funcionamento" do
        post :create, params: {hora_de_funcionamento: valid_attributes}, session: valid_session
        expect(response).to redirect_to(HoraDeFuncionamento.last)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: {hora_de_funcionamento: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {
          dia: "19/06",
          inicio: "9:00",
          fechamento: "18:00"
        }
      }

      it "updates the requested hora_de_funcionamento" do
        hora_de_funcionamento = HoraDeFuncionamento.create! valid_attributes
        put :update, params: {id: hora_de_funcionamento.to_param, hora_de_funcionamento: new_attributes}, session: valid_session
        hora_de_funcionamento.reload
        expect(hora_de_funcionamento).to be_valid
      end

      it "redirects to the hora_de_funcionamento" do
        hora_de_funcionamento = HoraDeFuncionamento.create! valid_attributes
        put :update, params: {id: hora_de_funcionamento.to_param, hora_de_funcionamento: valid_attributes}, session: valid_session
        expect(response).to redirect_to(hora_de_funcionamento)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        hora_de_funcionamento = HoraDeFuncionamento.create! valid_attributes
        put :update, params: {id: hora_de_funcionamento.to_param, hora_de_funcionamento: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested hora_de_funcionamento" do
      hora_de_funcionamento = HoraDeFuncionamento.create! valid_attributes
      expect {
        delete :destroy, params: {id: hora_de_funcionamento.to_param}, session: valid_session
      }.to change(HoraDeFuncionamento, :count).by(-1)
    end

    it "redirects to the hora_de_funcionamentos list" do
      hora_de_funcionamento = HoraDeFuncionamento.create! valid_attributes
      delete :destroy, params: {id: hora_de_funcionamento.to_param}, session: valid_session
      expect(response).to redirect_to(hora_de_funcionamentos_url)
    end
  end

end
